In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,-1]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,:-1]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)

scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [13]:
scaled_X_test.max()

1.02679563427227

In [14]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [15]:
model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [16]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 0s - loss: 0.6880 - acc: 0.5552
Epoch 2/50
 - 0s - loss: 0.6728 - acc: 0.5875
Epoch 3/50
 - 0s - loss: 0.6581 - acc: 0.6417
Epoch 4/50
 - 0s - loss: 0.6463 - acc: 0.6771
Epoch 5/50
 - 0s - loss: 0.6324 - acc: 0.7729
Epoch 6/50
 - 0s - loss: 0.6182 - acc: 0.7958
Epoch 7/50
 - 0s - loss: 0.6023 - acc: 0.7927
Epoch 8/50
 - 0s - loss: 0.5852 - acc: 0.8417
Epoch 9/50
 - 0s - loss: 0.5653 - acc: 0.8344
Epoch 10/50
 - 0s - loss: 0.5437 - acc: 0.8729
Epoch 11/50
 - 0s - loss: 0.5204 - acc: 0.8729
Epoch 12/50
 - 0s - loss: 0.4957 - acc: 0.8833
Epoch 13/50
 - 0s - loss: 0.4711 - acc: 0.8823
Epoch 14/50
 - 0s - loss: 0.4473 - acc: 0.8885
Epoch 15/50
 - 0s - loss: 0.4223 - acc: 0.8927
Epoch 16/50
 - 0s - loss: 0.3995 - acc: 0.8938
Epoch 17/50
 - 0s - loss: 0.3768 - acc: 0.8979
Epoch 18/50
 - 0s - loss: 0.3550 - acc: 0.9000
Epoch 19/50
 - 0s - loss: 0.3347 - acc: 0.9240
Epoch 20/50
 - 0s - loss: 0.3159 - acc: 0.9271
Epoch 21/50
 - 0s - loss: 0.2974 - acc: 0.9354
Epoch 22/50
 - 0s - lo

In [18]:
model.metrics_names

['loss', 'acc']

In [19]:
from sklearn.metrics import confusion_matrix,classification_report

In [20]:
y_pred = model.predict_classes(X_test)

In [21]:
confusion_matrix(y_test, y_pred)

array([[170,  59],
       [  0, 183]], dtype=int64)

In [22]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

        0.0       1.00      0.74      0.85       229
        1.0       0.76      1.00      0.86       183

avg / total       0.89      0.86      0.86       412



In [24]:
model.save('DATA\SavedData\kerasBasics.h5')

In [25]:
from keras.models import load_model

In [26]:
savedModel = load_model('DATA\SavedData\kerasBasics.h5')

In [27]:
y_pred2 = savedModel.predict_classes(X_test)

In [28]:
confusion_matrix(y_test, y_pred2)

array([[170,  59],
       [  0, 183]], dtype=int64)